### ISSUE TITLE
Lua 5.2+ support

### ISSUE THREAD

**Issue by checkraisefold** [latte-soft/wax#4]
Is there a way parts of the project can be rearchitected to not use `newproxy`, which I think is the only limitation for supporting at a minimum Lua 5.2?

**Comment by regginator** [comment]
*Maybe*, we could probably impl something like...

```lua
local newproxy = newproxy or function()
    return setmetatable({}, {})
end
```

... ?

**Comment by regginator** [comment]
Fixed up the upcoming release, closing this unless there's any other issues here 😄 

![image](https://github.com/latte-soft/wax/assets/56618074/0bf0885e-07b3-4c9d-8860-9607041dfeef)
